"use strict";

function amount(value){const n=Number(value);return Number.isFinite(n)?n:0;}
function sum(records, fields){return records.reduce((total,item)=>total+amount(fields.map(field=>item?.[field]).find(value=>value!==undefined)),0);}

/** Privacy-first financial insight engine. It reads established data and never changes it. */
class FinancialInsightService {
    /** Build a safe financial snapshot. @returns {Object} Aggregate financial values. @throws {never} Corrupt local values become empty arrays. */
    static snapshot(){let db={};try{db=JSON.parse(localStorage.getItem("SFM_DATABASE")||"{}");}catch(_error){db={};}const income=Array.isArray(db.income)?db.income:[];const expenses=Array.isArray(db.expenses)?db.expenses:[];const loans=Array.isArray(db.loans)?db.loans:[];const investments=Array.isArray(db.investments)?db.investments:[];const cards=Array.isArray(db.creditCards)?db.creditCards:[];const totalIncome=sum(income,["amount","incomeAmount"]);const totalExpense=sum(expenses,["amount","expenseAmount"]);const liabilities=sum(loans,["outstanding","balance","amount"])+sum(cards,["outstanding","balance"]);const investmentValue=sum(investments,["currentValue","value","amount"]);return{totalIncome,totalExpense,liabilities,investmentValue,savings:totalIncome-totalExpense,savingsRate:totalIncome?((totalIncome-totalExpense)/totalIncome)*100:0,expenseCount:expenses.length};}
    /** Generate explainable insights. @returns {Array<{title:string,message:string,severity:string,action:string}>} Recommendations. @throws {never} */
    static generate(){const s=this.snapshot(),items=[];if(!s.totalIncome&&!s.totalExpense)items.push({title:"Build your financial baseline",message:"Add income and expense records to unlock personalized trends and forecasts.",severity:"medium",action:"Start with this month's transactions."});if(s.totalExpense>s.totalIncome&&s.totalIncome>0)items.push({title:"Cash-flow risk detected",message:"Recorded expenses exceed income. Review discretionary categories before the next payment cycle.",severity:"high",action:"Reduce or defer non-essential spending."});else if(s.totalIncome>0)items.push({title:"Savings rate",message:`Your recorded savings rate is ${s.savingsRate.toFixed(1)}%.`,severity:s.savingsRate<10?"medium":"low",action:s.savingsRate<10?"Target a gradual increase toward 15–20%.":"Maintain the current saving discipline."});if(s.liabilities>0)items.push({title:"Debt exposure",message:`Outstanding recorded liabilities are ${money(s.liabilities)}.`,severity:s.liabilities>s.totalIncome?"high":"medium",action:"Prioritize high-interest balances and avoid missed due dates."});if(s.investmentValue>0)items.push({title:"Investment visibility",message:`Tracked investments currently total ${money(s.investmentValue)}.`,severity:"low",action:"Review allocation and goals at least quarterly."});if(s.expenseCount>0)items.push({title:"Data quality check",message:`Insights use ${s.expenseCount} recorded expenses and improve as records stay current.`,severity:"low",action:"Reconcile recent transactions before making decisions."});return items;}
}
function money(value){return new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(value||0);}
export { FinancialInsightService, money };
