'use strict';
const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..');
const configPath=path.join(root,'js','firebase','firebase-config.js');
const localPath=path.join(root,'js','firebase','firebase.local.config.js');
const authPath=path.join(root,'js','firebase','firebase-auth.js');
const loginPath=path.join(root,'js','login.js');
const source=fs.readFileSync(configPath,'utf8');
const auth=fs.readFileSync(authPath,'utf8');
const login=fs.readFileSync(loginPath,'utf8');
const failures=[];const check=(value,message)=>{if(!value)failures.push(message);};
check(fs.existsSync(localPath),'firebase.local.config.js is missing');
check(fs.readFileSync(localPath,'utf8').includes('firebaseLocalConfig = null'),'unknown credentials were not represented safely');
check(source.includes('"localhost", "127.0.0.1", "::1", "[::1]"'),'local hostname coverage is incomplete');
check(source.indexOf('source: "local-config-missing"')<source.indexOf('fetch("/__/firebase/init.json"'),'localhost does not stop before Hosting configuration');
check(!source.includes('apiKey: "sfm-pro-unconfigured"')&&!source.includes('projectId: "sfm-pro-unconfigured"'),'dummy Firebase configuration assignments remain');
check(source.includes('firebaseConfigurationStatus.configured\n    ?'),'Firebase initialization is not configuration-gated');
check(source.includes(': null;'),'unconfigured Firebase app does not resolve to null');
check(source.includes('Firebase Local Configuration Missing'),'local warning is missing');
check(source.includes('localConfigurationWarningLogged'),'single-warning guard is missing');
check(auth.includes('if (!firebaseAuth)'),'authentication adapter is not null-safe');
check(login.includes('button.dataset.firebaseUnavailable = "true"'),'Sign In is not disabled when unavailable');
check(login.includes('Please configure firebase.local.config.js'),'visible login configuration guidance is missing');
check(source.includes('source: "firebase-hosting"')&&source.includes('/__/firebase/init.json'),'Firebase Hosting resolution changed or is missing');
process.stdout.write(JSON.stringify({passed:13-failures.length,failed:failures.length,failures},null,2)+'\n');process.exitCode=failures.length?1:0;
