const PERMISSIONS = {
  SYSTEM_ADMIN: "SYSTEM_ADMIN",
  USER_READ: "USER_READ",
  USER_WRITE: "USER_WRITE",
  AUDIT_READ: "AUDIT_READ",
  SETTINGS_READ: "SETTINGS_READ",
  SETTINGS_WRITE: "SETTINGS_WRITE"
};

module.exports = {
  PERMISSIONS
};
